// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOotFFIBnExwlJNe_eliShATAB8ydb_SU',
    appId: '1:672968677764:web:d7d68e865793bd545025d1',
    messagingSenderId: '672968677764',
    projectId: 'mla-project-1',
    authDomain: 'mla-project-1.firebaseapp.com',
    storageBucket: 'mla-project-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUiFSkdYDi8soFzXFP_Ye8opY8fN08kM',
    appId: '1:672968677764:android:b7c58aaf27edeede5025d1',
    messagingSenderId: '672968677764',
    projectId: 'mla-project-1',
    storageBucket: 'mla-project-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWd2PMZl3UlwfTX9UhZnx8iBYTgjrrWUk',
    appId: '1:672968677764:ios:abb499b6f2c5b8135025d1',
    messagingSenderId: '672968677764',
    projectId: 'mla-project-1',
    storageBucket: 'mla-project-1.firebasestorage.app',
    iosBundleId: 'com.example.proNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWd2PMZl3UlwfTX9UhZnx8iBYTgjrrWUk',
    appId: '1:672968677764:ios:abb499b6f2c5b8135025d1',
    messagingSenderId: '672968677764',
    projectId: 'mla-project-1',
    storageBucket: 'mla-project-1.firebasestorage.app',
    iosBundleId: 'com.example.proNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf5nszYFwE2uUbFeSvlBejAC-DP-Qbytk',
    appId: '1:181465237999:web:3e0e092f9e9c4fdfe08e1a',
    messagingSenderId: '181465237999',
    projectId: 'prosocialnetwork',
    authDomain: 'prosocialnetwork.firebaseapp.com',
    storageBucket: 'prosocialnetwork.firebasestorage.app',
  );

}