// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5nszYFwE2uUbFeSvlBejAC-DP-Qbytk',
    appId: '1:181465237999:web:f1f54d924bf97ef0e08e1a',
    messagingSenderId: '181465237999',
    projectId: 'prosocialnetwork',
    authDomain: 'prosocialnetwork.firebaseapp.com',
    storageBucket: 'prosocialnetwork.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2Z4hqqbbWw6LH7rIrRaOVDJUVI85URg',
    appId: '1:181465237999:android:7d6529c46a04a0afe08e1a',
    messagingSenderId: '181465237999',
    projectId: 'prosocialnetwork',
    storageBucket: 'prosocialnetwork.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJXLMdo3LL5n_1DgP76ux1Dxa5DI6D0VA',
    appId: '1:181465237999:ios:f97368e9e6842424e08e1a',
    messagingSenderId: '181465237999',
    projectId: 'prosocialnetwork',
    storageBucket: 'prosocialnetwork.firebasestorage.app',
    iosBundleId: 'com.example.proNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJXLMdo3LL5n_1DgP76ux1Dxa5DI6D0VA',
    appId: '1:181465237999:ios:f97368e9e6842424e08e1a',
    messagingSenderId: '181465237999',
    projectId: 'prosocialnetwork',
    storageBucket: 'prosocialnetwork.firebasestorage.app',
    iosBundleId: 'com.example.proNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf5nszYFwE2uUbFeSvlBejAC-DP-Qbytk',
    appId: '1:181465237999:web:3e0e092f9e9c4fdfe08e1a',
    messagingSenderId: '181465237999',
    projectId: 'prosocialnetwork',
    authDomain: 'prosocialnetwork.firebaseapp.com',
    storageBucket: 'prosocialnetwork.firebasestorage.app',
  );
}
